// Code generated by protoc-gen-go. DO NOT EDIT.
// source: WarWithJoshAPIMessages.proto

package web

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MoveMessage struct {
	AiScore              float32  `protobuf:"fixed32,1,opt,name=AiScore,proto3" json:"AiScore,omitempty"`
	AiBid                uint32   `protobuf:"varint,2,opt,name=AiBid,proto3" json:"AiBid,omitempty"`
	PlayerScore          float32  `protobuf:"fixed32,3,opt,name=PlayerScore,proto3" json:"PlayerScore,omitempty"`
	PlayerBid            uint32   `protobuf:"varint,4,opt,name=PlayerBid,proto3" json:"PlayerBid,omitempty"`
	HandValue            uint32   `protobuf:"varint,5,opt,name=HandValue,proto3" json:"HandValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveMessage) Reset()         { *m = MoveMessage{} }
func (m *MoveMessage) String() string { return proto.CompactTextString(m) }
func (*MoveMessage) ProtoMessage()    {}
func (*MoveMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_WarWithJoshAPIMessages_d797708d4580c3ee, []int{0}
}
func (m *MoveMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveMessage.Unmarshal(m, b)
}
func (m *MoveMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveMessage.Marshal(b, m, deterministic)
}
func (dst *MoveMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveMessage.Merge(dst, src)
}
func (m *MoveMessage) XXX_Size() int {
	return xxx_messageInfo_MoveMessage.Size(m)
}
func (m *MoveMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MoveMessage proto.InternalMessageInfo

func (m *MoveMessage) GetAiScore() float32 {
	if m != nil {
		return m.AiScore
	}
	return 0
}

func (m *MoveMessage) GetAiBid() uint32 {
	if m != nil {
		return m.AiBid
	}
	return 0
}

func (m *MoveMessage) GetPlayerScore() float32 {
	if m != nil {
		return m.PlayerScore
	}
	return 0
}

func (m *MoveMessage) GetPlayerBid() uint32 {
	if m != nil {
		return m.PlayerBid
	}
	return 0
}

func (m *MoveMessage) GetHandValue() uint32 {
	if m != nil {
		return m.HandValue
	}
	return 0
}

type TrickCompletedMessage struct {
	Move                 *MoveMessage `protobuf:"bytes,1,opt,name=Move,proto3" json:"Move,omitempty"`
	TricksRemaining      uint32       `protobuf:"varint,2,opt,name=TricksRemaining,proto3" json:"TricksRemaining,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TrickCompletedMessage) Reset()         { *m = TrickCompletedMessage{} }
func (m *TrickCompletedMessage) String() string { return proto.CompactTextString(m) }
func (*TrickCompletedMessage) ProtoMessage()    {}
func (*TrickCompletedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_WarWithJoshAPIMessages_d797708d4580c3ee, []int{1}
}
func (m *TrickCompletedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrickCompletedMessage.Unmarshal(m, b)
}
func (m *TrickCompletedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrickCompletedMessage.Marshal(b, m, deterministic)
}
func (dst *TrickCompletedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrickCompletedMessage.Merge(dst, src)
}
func (m *TrickCompletedMessage) XXX_Size() int {
	return xxx_messageInfo_TrickCompletedMessage.Size(m)
}
func (m *TrickCompletedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TrickCompletedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TrickCompletedMessage proto.InternalMessageInfo

func (m *TrickCompletedMessage) GetMove() *MoveMessage {
	if m != nil {
		return m.Move
	}
	return nil
}

func (m *TrickCompletedMessage) GetTricksRemaining() uint32 {
	if m != nil {
		return m.TricksRemaining
	}
	return 0
}

type AiDecidedMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AiDecidedMessage) Reset()         { *m = AiDecidedMessage{} }
func (m *AiDecidedMessage) String() string { return proto.CompactTextString(m) }
func (*AiDecidedMessage) ProtoMessage()    {}
func (*AiDecidedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_WarWithJoshAPIMessages_d797708d4580c3ee, []int{2}
}
func (m *AiDecidedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AiDecidedMessage.Unmarshal(m, b)
}
func (m *AiDecidedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AiDecidedMessage.Marshal(b, m, deterministic)
}
func (dst *AiDecidedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AiDecidedMessage.Merge(dst, src)
}
func (m *AiDecidedMessage) XXX_Size() int {
	return xxx_messageInfo_AiDecidedMessage.Size(m)
}
func (m *AiDecidedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AiDecidedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AiDecidedMessage proto.InternalMessageInfo

type TrickDecidedMessage struct {
	TrickPoints          uint32   `protobuf:"varint,1,opt,name=TrickPoints,proto3" json:"TrickPoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrickDecidedMessage) Reset()         { *m = TrickDecidedMessage{} }
func (m *TrickDecidedMessage) String() string { return proto.CompactTextString(m) }
func (*TrickDecidedMessage) ProtoMessage()    {}
func (*TrickDecidedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_WarWithJoshAPIMessages_d797708d4580c3ee, []int{3}
}
func (m *TrickDecidedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrickDecidedMessage.Unmarshal(m, b)
}
func (m *TrickDecidedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrickDecidedMessage.Marshal(b, m, deterministic)
}
func (dst *TrickDecidedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrickDecidedMessage.Merge(dst, src)
}
func (m *TrickDecidedMessage) XXX_Size() int {
	return xxx_messageInfo_TrickDecidedMessage.Size(m)
}
func (m *TrickDecidedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TrickDecidedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TrickDecidedMessage proto.InternalMessageInfo

func (m *TrickDecidedMessage) GetTrickPoints() uint32 {
	if m != nil {
		return m.TrickPoints
	}
	return 0
}

type PlayerDecidedMessage struct {
	Value                uint32   `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerDecidedMessage) Reset()         { *m = PlayerDecidedMessage{} }
func (m *PlayerDecidedMessage) String() string { return proto.CompactTextString(m) }
func (*PlayerDecidedMessage) ProtoMessage()    {}
func (*PlayerDecidedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_WarWithJoshAPIMessages_d797708d4580c3ee, []int{4}
}
func (m *PlayerDecidedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerDecidedMessage.Unmarshal(m, b)
}
func (m *PlayerDecidedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerDecidedMessage.Marshal(b, m, deterministic)
}
func (dst *PlayerDecidedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerDecidedMessage.Merge(dst, src)
}
func (m *PlayerDecidedMessage) XXX_Size() int {
	return xxx_messageInfo_PlayerDecidedMessage.Size(m)
}
func (m *PlayerDecidedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerDecidedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerDecidedMessage proto.InternalMessageInfo

func (m *PlayerDecidedMessage) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type ResultsMessage struct {
	AiScore              float32  `protobuf:"fixed32,1,opt,name=AiScore,proto3" json:"AiScore,omitempty"`
	PlayerScore          float32  `protobuf:"fixed32,2,opt,name=PlayerScore,proto3" json:"PlayerScore,omitempty"`
	AiTotalGames         uint32   `protobuf:"varint,3,opt,name=AiTotalGames,proto3" json:"AiTotalGames,omitempty"`
	PlayerTotalGames     uint32   `protobuf:"varint,4,opt,name=PlayerTotalGames,proto3" json:"PlayerTotalGames,omitempty"`
	AiWinPercentage      float32  `protobuf:"fixed32,5,opt,name=AiWinPercentage,proto3" json:"AiWinPercentage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultsMessage) Reset()         { *m = ResultsMessage{} }
func (m *ResultsMessage) String() string { return proto.CompactTextString(m) }
func (*ResultsMessage) ProtoMessage()    {}
func (*ResultsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_WarWithJoshAPIMessages_d797708d4580c3ee, []int{5}
}
func (m *ResultsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultsMessage.Unmarshal(m, b)
}
func (m *ResultsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultsMessage.Marshal(b, m, deterministic)
}
func (dst *ResultsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultsMessage.Merge(dst, src)
}
func (m *ResultsMessage) XXX_Size() int {
	return xxx_messageInfo_ResultsMessage.Size(m)
}
func (m *ResultsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ResultsMessage proto.InternalMessageInfo

func (m *ResultsMessage) GetAiScore() float32 {
	if m != nil {
		return m.AiScore
	}
	return 0
}

func (m *ResultsMessage) GetPlayerScore() float32 {
	if m != nil {
		return m.PlayerScore
	}
	return 0
}

func (m *ResultsMessage) GetAiTotalGames() uint32 {
	if m != nil {
		return m.AiTotalGames
	}
	return 0
}

func (m *ResultsMessage) GetPlayerTotalGames() uint32 {
	if m != nil {
		return m.PlayerTotalGames
	}
	return 0
}

func (m *ResultsMessage) GetAiWinPercentage() float32 {
	if m != nil {
		return m.AiWinPercentage
	}
	return 0
}

type StartGameMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartGameMessage) Reset()         { *m = StartGameMessage{} }
func (m *StartGameMessage) String() string { return proto.CompactTextString(m) }
func (*StartGameMessage) ProtoMessage()    {}
func (*StartGameMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_WarWithJoshAPIMessages_d797708d4580c3ee, []int{6}
}
func (m *StartGameMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGameMessage.Unmarshal(m, b)
}
func (m *StartGameMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGameMessage.Marshal(b, m, deterministic)
}
func (dst *StartGameMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGameMessage.Merge(dst, src)
}
func (m *StartGameMessage) XXX_Size() int {
	return xxx_messageInfo_StartGameMessage.Size(m)
}
func (m *StartGameMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGameMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StartGameMessage proto.InternalMessageInfo

type EndSessionMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndSessionMessage) Reset()         { *m = EndSessionMessage{} }
func (m *EndSessionMessage) String() string { return proto.CompactTextString(m) }
func (*EndSessionMessage) ProtoMessage()    {}
func (*EndSessionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_WarWithJoshAPIMessages_d797708d4580c3ee, []int{7}
}
func (m *EndSessionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndSessionMessage.Unmarshal(m, b)
}
func (m *EndSessionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndSessionMessage.Marshal(b, m, deterministic)
}
func (dst *EndSessionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndSessionMessage.Merge(dst, src)
}
func (m *EndSessionMessage) XXX_Size() int {
	return xxx_messageInfo_EndSessionMessage.Size(m)
}
func (m *EndSessionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EndSessionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EndSessionMessage proto.InternalMessageInfo

type SetAiMessage struct {
	AiName               string   `protobuf:"bytes,1,opt,name=AiName,proto3" json:"AiName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAiMessage) Reset()         { *m = SetAiMessage{} }
func (m *SetAiMessage) String() string { return proto.CompactTextString(m) }
func (*SetAiMessage) ProtoMessage()    {}
func (*SetAiMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_WarWithJoshAPIMessages_d797708d4580c3ee, []int{8}
}
func (m *SetAiMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAiMessage.Unmarshal(m, b)
}
func (m *SetAiMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAiMessage.Marshal(b, m, deterministic)
}
func (dst *SetAiMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAiMessage.Merge(dst, src)
}
func (m *SetAiMessage) XXX_Size() int {
	return xxx_messageInfo_SetAiMessage.Size(m)
}
func (m *SetAiMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAiMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SetAiMessage proto.InternalMessageInfo

func (m *SetAiMessage) GetAiName() string {
	if m != nil {
		return m.AiName
	}
	return ""
}

type ErrorMessage struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorMessage) Reset()         { *m = ErrorMessage{} }
func (m *ErrorMessage) String() string { return proto.CompactTextString(m) }
func (*ErrorMessage) ProtoMessage()    {}
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_WarWithJoshAPIMessages_d797708d4580c3ee, []int{9}
}
func (m *ErrorMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorMessage.Unmarshal(m, b)
}
func (m *ErrorMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorMessage.Marshal(b, m, deterministic)
}
func (dst *ErrorMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorMessage.Merge(dst, src)
}
func (m *ErrorMessage) XXX_Size() int {
	return xxx_messageInfo_ErrorMessage.Size(m)
}
func (m *ErrorMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorMessage proto.InternalMessageInfo

func (m *ErrorMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Wrapper struct {
	Payload              *any.Any `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wrapper) Reset()         { *m = Wrapper{} }
func (m *Wrapper) String() string { return proto.CompactTextString(m) }
func (*Wrapper) ProtoMessage()    {}
func (*Wrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_WarWithJoshAPIMessages_d797708d4580c3ee, []int{10}
}
func (m *Wrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wrapper.Unmarshal(m, b)
}
func (m *Wrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wrapper.Marshal(b, m, deterministic)
}
func (dst *Wrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wrapper.Merge(dst, src)
}
func (m *Wrapper) XXX_Size() int {
	return xxx_messageInfo_Wrapper.Size(m)
}
func (m *Wrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_Wrapper.DiscardUnknown(m)
}

var xxx_messageInfo_Wrapper proto.InternalMessageInfo

func (m *Wrapper) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*MoveMessage)(nil), "web.MoveMessage")
	proto.RegisterType((*TrickCompletedMessage)(nil), "web.TrickCompletedMessage")
	proto.RegisterType((*AiDecidedMessage)(nil), "web.AiDecidedMessage")
	proto.RegisterType((*TrickDecidedMessage)(nil), "web.TrickDecidedMessage")
	proto.RegisterType((*PlayerDecidedMessage)(nil), "web.PlayerDecidedMessage")
	proto.RegisterType((*ResultsMessage)(nil), "web.ResultsMessage")
	proto.RegisterType((*StartGameMessage)(nil), "web.StartGameMessage")
	proto.RegisterType((*EndSessionMessage)(nil), "web.EndSessionMessage")
	proto.RegisterType((*SetAiMessage)(nil), "web.SetAiMessage")
	proto.RegisterType((*ErrorMessage)(nil), "web.ErrorMessage")
	proto.RegisterType((*Wrapper)(nil), "web.Wrapper")
}

func init() {
	proto.RegisterFile("WarWithJoshAPIMessages.proto", fileDescriptor_WarWithJoshAPIMessages_d797708d4580c3ee)
}

var fileDescriptor_WarWithJoshAPIMessages_d797708d4580c3ee = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x6e, 0x13, 0x31,
	0x10, 0xc6, 0x95, 0xf4, 0x4f, 0xd4, 0x49, 0x02, 0xc1, 0x0d, 0x28, 0xa0, 0x1e, 0x2a, 0x0b, 0xa1,
	0x08, 0xa1, 0xad, 0x54, 0x0e, 0x88, 0xa3, 0x81, 0x8a, 0x3f, 0x52, 0x51, 0xe4, 0x54, 0xe4, 0xec,
	0x64, 0x87, 0xed, 0x88, 0x8d, 0xbd, 0xb2, 0x1d, 0x50, 0x9e, 0x85, 0xf7, 0xe1, 0xb9, 0xd8, 0xb5,
	0x77, 0xcb, 0x36, 0x39, 0x70, 0xdb, 0xf9, 0xcd, 0x7c, 0xda, 0xf9, 0xbe, 0x31, 0x9c, 0x2d, 0x94,
	0x5d, 0x90, 0xbf, 0xfd, 0x62, 0xdc, 0xad, 0x98, 0x7d, 0xbe, 0x46, 0xe7, 0x54, 0x86, 0x2e, 0x29,
	0xac, 0xf1, 0x86, 0x1d, 0xfc, 0xc2, 0xe5, 0xb3, 0xa7, 0x99, 0x31, 0x59, 0x8e, 0x17, 0x01, 0x2d,
	0x37, 0xdf, 0x2f, 0x94, 0xde, 0xc6, 0x3e, 0xff, 0xdd, 0x81, 0xfe, 0xb5, 0xf9, 0x89, 0xb5, 0x8c,
	0x4d, 0xa0, 0x27, 0x68, 0xbe, 0x32, 0x16, 0x27, 0x9d, 0xf3, 0xce, 0xb4, 0x2b, 0x9b, 0x92, 0x8d,
	0xe1, 0x48, 0xd0, 0x3b, 0x4a, 0x27, 0xdd, 0x92, 0x0f, 0x65, 0x2c, 0xd8, 0x39, 0xf4, 0x67, 0xb9,
	0xda, 0xa2, 0x8d, 0x9a, 0x83, 0xa0, 0x69, 0x23, 0x76, 0x06, 0x27, 0xb1, 0xac, 0xb4, 0x87, 0x41,
	0xfb, 0x0f, 0x54, 0xdd, 0x4f, 0x4a, 0xa7, 0xdf, 0x54, 0xbe, 0xc1, 0xc9, 0x51, 0xec, 0xde, 0x01,
	0x9e, 0xc1, 0xe3, 0x1b, 0x4b, 0xab, 0x1f, 0xef, 0xcd, 0xba, 0xc8, 0xd1, 0x63, 0xda, 0xac, 0xf9,
	0x1c, 0x0e, 0xab, 0xad, 0xc3, 0x8e, 0xfd, 0xcb, 0x51, 0x52, 0xba, 0x4c, 0x5a, 0x36, 0x64, 0xe8,
	0xb2, 0x29, 0x3c, 0x0c, 0x72, 0x27, 0x71, 0xad, 0x48, 0x93, 0xce, 0xea, 0xe5, 0x77, 0x31, 0x67,
	0x30, 0x12, 0xf4, 0x01, 0x57, 0x94, 0xde, 0xfd, 0x83, 0xbf, 0x81, 0xd3, 0x30, 0x76, 0x1f, 0x57,
	0x8e, 0x03, 0x9e, 0x19, 0xd2, 0xde, 0x85, 0x0d, 0x86, 0xb2, 0x8d, 0xf8, 0x2b, 0x18, 0x47, 0x83,
	0x3b, 0xca, 0x32, 0xc1, 0xe8, 0x33, 0x6a, 0x62, 0xc1, 0xff, 0x74, 0xe0, 0x81, 0x44, 0xb7, 0xc9,
	0xbd, 0xfb, 0xff, 0x11, 0x76, 0xe2, 0xee, 0xee, 0xc7, 0xcd, 0x61, 0x20, 0xe8, 0xc6, 0x78, 0x95,
	0x7f, 0x54, 0x6b, 0x74, 0xe1, 0x22, 0x43, 0x79, 0x8f, 0xb1, 0x97, 0x30, 0x8a, 0x92, 0xd6, 0x5c,
	0xbc, 0xcc, 0x1e, 0xaf, 0x32, 0x14, 0xb4, 0x20, 0x3d, 0x43, 0xbb, 0x42, 0xed, 0xcb, 0xf5, 0xc2,
	0x99, 0xba, 0x72, 0x17, 0x57, 0x19, 0xce, 0xbd, 0xb2, 0xbe, 0xd2, 0x35, 0x19, 0x9e, 0xc2, 0xa3,
	0x2b, 0x9d, 0xce, 0xcb, 0x8a, 0x8c, 0x6e, 0xe0, 0x0b, 0x18, 0xcc, 0xd1, 0x0b, 0x6a, 0xec, 0x3e,
	0x81, 0x63, 0x41, 0x5f, 0x4b, 0x55, 0x70, 0x7b, 0x22, 0xeb, 0x8a, 0x4f, 0x61, 0x70, 0x65, 0xad,
	0xb1, 0xad, 0x58, 0xea, 0xcf, 0x7a, 0xb0, 0x29, 0xf9, 0x5b, 0xe8, 0x2d, 0xac, 0x2a, 0x0a, 0xb4,
	0x2c, 0x81, 0x5e, 0xa1, 0xb6, 0xb9, 0x51, 0xf1, 0xa1, 0xf6, 0x2f, 0xc7, 0x49, 0x7c, 0xfd, 0x49,
	0xf3, 0xfa, 0x13, 0xa1, 0xb7, 0xb2, 0x19, 0x5a, 0x1e, 0x07, 0xfc, 0xfa, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x28, 0x6b, 0xc3, 0x21, 0x47, 0x03, 0x00, 0x00,
}
