// Code generated by protoc-gen-go. DO NOT EDIT.
// source: WarWithJoshAPIMessages.proto

package web

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Move struct {
	AiScore              float32  `protobuf:"fixed32,1,opt,name=AiScore,proto3" json:"AiScore,omitempty"`
	AiBid                int32    `protobuf:"varint,2,opt,name=AiBid,proto3" json:"AiBid,omitempty"`
	PlayerScore          float32  `protobuf:"fixed32,3,opt,name=PlayerScore,proto3" json:"PlayerScore,omitempty"`
	PlayerBid            int32    `protobuf:"varint,4,opt,name=PlayerBid,proto3" json:"PlayerBid,omitempty"`
	HandValue            int32    `protobuf:"varint,5,opt,name=HandValue,proto3" json:"HandValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Move) Reset()         { *m = Move{} }
func (m *Move) String() string { return proto.CompactTextString(m) }
func (*Move) ProtoMessage()    {}
func (*Move) Descriptor() ([]byte, []int) {
	return fileDescriptor_09dd4463dfc3c7cc, []int{0}
}

func (m *Move) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Move.Unmarshal(m, b)
}
func (m *Move) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Move.Marshal(b, m, deterministic)
}
func (m *Move) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Move.Merge(m, src)
}
func (m *Move) XXX_Size() int {
	return xxx_messageInfo_Move.Size(m)
}
func (m *Move) XXX_DiscardUnknown() {
	xxx_messageInfo_Move.DiscardUnknown(m)
}

var xxx_messageInfo_Move proto.InternalMessageInfo

func (m *Move) GetAiScore() float32 {
	if m != nil {
		return m.AiScore
	}
	return 0
}

func (m *Move) GetAiBid() int32 {
	if m != nil {
		return m.AiBid
	}
	return 0
}

func (m *Move) GetPlayerScore() float32 {
	if m != nil {
		return m.PlayerScore
	}
	return 0
}

func (m *Move) GetPlayerBid() int32 {
	if m != nil {
		return m.PlayerBid
	}
	return 0
}

func (m *Move) GetHandValue() int32 {
	if m != nil {
		return m.HandValue
	}
	return 0
}

type TrickCompleted struct {
	Move                 *Move    `protobuf:"bytes,1,opt,name=Move,proto3" json:"Move,omitempty"`
	TricksRemaining      int32    `protobuf:"varint,2,opt,name=TricksRemaining,proto3" json:"TricksRemaining,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrickCompleted) Reset()         { *m = TrickCompleted{} }
func (m *TrickCompleted) String() string { return proto.CompactTextString(m) }
func (*TrickCompleted) ProtoMessage()    {}
func (*TrickCompleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_09dd4463dfc3c7cc, []int{1}
}

func (m *TrickCompleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrickCompleted.Unmarshal(m, b)
}
func (m *TrickCompleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrickCompleted.Marshal(b, m, deterministic)
}
func (m *TrickCompleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrickCompleted.Merge(m, src)
}
func (m *TrickCompleted) XXX_Size() int {
	return xxx_messageInfo_TrickCompleted.Size(m)
}
func (m *TrickCompleted) XXX_DiscardUnknown() {
	xxx_messageInfo_TrickCompleted.DiscardUnknown(m)
}

var xxx_messageInfo_TrickCompleted proto.InternalMessageInfo

func (m *TrickCompleted) GetMove() *Move {
	if m != nil {
		return m.Move
	}
	return nil
}

func (m *TrickCompleted) GetTricksRemaining() int32 {
	if m != nil {
		return m.TricksRemaining
	}
	return 0
}

type AiDecided struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AiDecided) Reset()         { *m = AiDecided{} }
func (m *AiDecided) String() string { return proto.CompactTextString(m) }
func (*AiDecided) ProtoMessage()    {}
func (*AiDecided) Descriptor() ([]byte, []int) {
	return fileDescriptor_09dd4463dfc3c7cc, []int{2}
}

func (m *AiDecided) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AiDecided.Unmarshal(m, b)
}
func (m *AiDecided) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AiDecided.Marshal(b, m, deterministic)
}
func (m *AiDecided) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AiDecided.Merge(m, src)
}
func (m *AiDecided) XXX_Size() int {
	return xxx_messageInfo_AiDecided.Size(m)
}
func (m *AiDecided) XXX_DiscardUnknown() {
	xxx_messageInfo_AiDecided.DiscardUnknown(m)
}

var xxx_messageInfo_AiDecided proto.InternalMessageInfo

type TrickDecided struct {
	TrickPoints          int32    `protobuf:"varint,1,opt,name=TrickPoints,proto3" json:"TrickPoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrickDecided) Reset()         { *m = TrickDecided{} }
func (m *TrickDecided) String() string { return proto.CompactTextString(m) }
func (*TrickDecided) ProtoMessage()    {}
func (*TrickDecided) Descriptor() ([]byte, []int) {
	return fileDescriptor_09dd4463dfc3c7cc, []int{3}
}

func (m *TrickDecided) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrickDecided.Unmarshal(m, b)
}
func (m *TrickDecided) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrickDecided.Marshal(b, m, deterministic)
}
func (m *TrickDecided) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrickDecided.Merge(m, src)
}
func (m *TrickDecided) XXX_Size() int {
	return xxx_messageInfo_TrickDecided.Size(m)
}
func (m *TrickDecided) XXX_DiscardUnknown() {
	xxx_messageInfo_TrickDecided.DiscardUnknown(m)
}

var xxx_messageInfo_TrickDecided proto.InternalMessageInfo

func (m *TrickDecided) GetTrickPoints() int32 {
	if m != nil {
		return m.TrickPoints
	}
	return 0
}

type PlayerDecided struct {
	Value                int32    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerDecided) Reset()         { *m = PlayerDecided{} }
func (m *PlayerDecided) String() string { return proto.CompactTextString(m) }
func (*PlayerDecided) ProtoMessage()    {}
func (*PlayerDecided) Descriptor() ([]byte, []int) {
	return fileDescriptor_09dd4463dfc3c7cc, []int{4}
}

func (m *PlayerDecided) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerDecided.Unmarshal(m, b)
}
func (m *PlayerDecided) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerDecided.Marshal(b, m, deterministic)
}
func (m *PlayerDecided) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerDecided.Merge(m, src)
}
func (m *PlayerDecided) XXX_Size() int {
	return xxx_messageInfo_PlayerDecided.Size(m)
}
func (m *PlayerDecided) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerDecided.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerDecided proto.InternalMessageInfo

func (m *PlayerDecided) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Results struct {
	AiScore              float32  `protobuf:"fixed32,1,opt,name=AiScore,proto3" json:"AiScore,omitempty"`
	PlayerScore          float32  `protobuf:"fixed32,2,opt,name=PlayerScore,proto3" json:"PlayerScore,omitempty"`
	AiTotalGames         int32    `protobuf:"varint,3,opt,name=AiTotalGames,proto3" json:"AiTotalGames,omitempty"`
	PlayerTotalGames     int32    `protobuf:"varint,4,opt,name=PlayerTotalGames,proto3" json:"PlayerTotalGames,omitempty"`
	AiWinPercentage      float32  `protobuf:"fixed32,5,opt,name=AiWinPercentage,proto3" json:"AiWinPercentage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Results) Reset()         { *m = Results{} }
func (m *Results) String() string { return proto.CompactTextString(m) }
func (*Results) ProtoMessage()    {}
func (*Results) Descriptor() ([]byte, []int) {
	return fileDescriptor_09dd4463dfc3c7cc, []int{5}
}

func (m *Results) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Results.Unmarshal(m, b)
}
func (m *Results) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Results.Marshal(b, m, deterministic)
}
func (m *Results) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Results.Merge(m, src)
}
func (m *Results) XXX_Size() int {
	return xxx_messageInfo_Results.Size(m)
}
func (m *Results) XXX_DiscardUnknown() {
	xxx_messageInfo_Results.DiscardUnknown(m)
}

var xxx_messageInfo_Results proto.InternalMessageInfo

func (m *Results) GetAiScore() float32 {
	if m != nil {
		return m.AiScore
	}
	return 0
}

func (m *Results) GetPlayerScore() float32 {
	if m != nil {
		return m.PlayerScore
	}
	return 0
}

func (m *Results) GetAiTotalGames() int32 {
	if m != nil {
		return m.AiTotalGames
	}
	return 0
}

func (m *Results) GetPlayerTotalGames() int32 {
	if m != nil {
		return m.PlayerTotalGames
	}
	return 0
}

func (m *Results) GetAiWinPercentage() float32 {
	if m != nil {
		return m.AiWinPercentage
	}
	return 0
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_09dd4463dfc3c7cc, []int{6}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Wrapper struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload              *any.Any `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wrapper) Reset()         { *m = Wrapper{} }
func (m *Wrapper) String() string { return proto.CompactTextString(m) }
func (*Wrapper) ProtoMessage()    {}
func (*Wrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_09dd4463dfc3c7cc, []int{7}
}

func (m *Wrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wrapper.Unmarshal(m, b)
}
func (m *Wrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wrapper.Marshal(b, m, deterministic)
}
func (m *Wrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wrapper.Merge(m, src)
}
func (m *Wrapper) XXX_Size() int {
	return xxx_messageInfo_Wrapper.Size(m)
}
func (m *Wrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_Wrapper.DiscardUnknown(m)
}

var xxx_messageInfo_Wrapper proto.InternalMessageInfo

func (m *Wrapper) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Wrapper) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Move)(nil), "web.Move")
	proto.RegisterType((*TrickCompleted)(nil), "web.TrickCompleted")
	proto.RegisterType((*AiDecided)(nil), "web.AiDecided")
	proto.RegisterType((*TrickDecided)(nil), "web.TrickDecided")
	proto.RegisterType((*PlayerDecided)(nil), "web.PlayerDecided")
	proto.RegisterType((*Results)(nil), "web.Results")
	proto.RegisterType((*Error)(nil), "web.Error")
	proto.RegisterType((*Wrapper)(nil), "web.Wrapper")
}

func init() { proto.RegisterFile("WarWithJoshAPIMessages.proto", fileDescriptor_09dd4463dfc3c7cc) }

var fileDescriptor_09dd4463dfc3c7cc = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xdd, 0x8a, 0xd4, 0x40,
	0x10, 0x85, 0xc9, 0xec, 0xc4, 0x61, 0x2a, 0xeb, 0x0f, 0xcd, 0x5c, 0x44, 0x59, 0x61, 0x6c, 0x10,
	0x06, 0x2f, 0xb2, 0xb2, 0x3e, 0x41, 0xfc, 0xc1, 0x1f, 0x18, 0x08, 0xed, 0x62, 0xf0, 0xb2, 0x93,
	0x94, 0xd9, 0xc6, 0x4c, 0x77, 0xe8, 0xee, 0x71, 0xc9, 0x7b, 0xf8, 0x3e, 0xbe, 0x9a, 0xa4, 0x6b,
	0xa2, 0xe3, 0x2c, 0x78, 0x97, 0xf3, 0x55, 0x1d, 0x72, 0xfa, 0x50, 0x70, 0x51, 0x4a, 0x5b, 0x2a,
	0x7f, 0xf3, 0xc9, 0xb8, 0x9b, 0xbc, 0xf8, 0xb8, 0x45, 0xe7, 0x64, 0x8b, 0x2e, 0xeb, 0xad, 0xf1,
	0x86, 0x9d, 0xdd, 0x62, 0xf5, 0xe4, 0x71, 0x6b, 0x4c, 0xdb, 0xe1, 0x65, 0x40, 0xd5, 0xfe, 0xdb,
	0xa5, 0xd4, 0x03, 0xcd, 0xf9, 0xcf, 0x08, 0xe6, 0x5b, 0xf3, 0x03, 0x59, 0x0a, 0x8b, 0x5c, 0x7d,
	0xae, 0x8d, 0xc5, 0x34, 0x5a, 0x47, 0x9b, 0x99, 0x98, 0x24, 0x5b, 0x41, 0x9c, 0xab, 0xd7, 0xaa,
	0x49, 0x67, 0xeb, 0x68, 0x13, 0x0b, 0x12, 0x6c, 0x0d, 0x49, 0xd1, 0xc9, 0x01, 0x2d, 0x79, 0xce,
	0x82, 0xe7, 0x18, 0xb1, 0x0b, 0x58, 0x92, 0x1c, 0xbd, 0xf3, 0xe0, 0xfd, 0x0b, 0xc6, 0xe9, 0x07,
	0xa9, 0x9b, 0x2f, 0xb2, 0xdb, 0x63, 0x1a, 0xd3, 0xf4, 0x0f, 0xe0, 0x5f, 0xe1, 0xc1, 0xb5, 0x55,
	0xf5, 0xf7, 0x37, 0x66, 0xd7, 0x77, 0xe8, 0xb1, 0x61, 0x4f, 0x29, 0x67, 0x08, 0x97, 0x5c, 0x2d,
	0xb3, 0x5b, 0xac, 0xb2, 0x11, 0x08, 0x8a, 0xbf, 0x81, 0x87, 0xc1, 0xe0, 0x04, 0xee, 0xa4, 0xd2,
	0x4a, 0xb7, 0x87, 0xb8, 0xa7, 0x98, 0x27, 0xb0, 0xcc, 0xd5, 0x5b, 0xac, 0x55, 0x83, 0x0d, 0x7f,
	0x09, 0xe7, 0x61, 0x7e, 0xd0, 0xe3, 0xab, 0x82, 0x2e, 0x8c, 0xd2, 0xde, 0x85, 0x9f, 0xc5, 0xe2,
	0x18, 0xf1, 0xe7, 0x70, 0x9f, 0x1e, 0x31, 0x59, 0x56, 0x10, 0xd3, 0x23, 0x68, 0x99, 0x04, 0xff,
	0x15, 0xc1, 0x42, 0xa0, 0xdb, 0x77, 0xde, 0xfd, 0xa7, 0xda, 0x93, 0x12, 0x67, 0x77, 0x4b, 0xe4,
	0x70, 0x9e, 0xab, 0x6b, 0xe3, 0x65, 0xf7, 0x5e, 0xee, 0xd0, 0x85, 0x9e, 0x63, 0xf1, 0x0f, 0x63,
	0x2f, 0xe0, 0x11, 0x59, 0x8e, 0xf6, 0xa8, 0xef, 0x3b, 0x7c, 0xec, 0x29, 0x57, 0xa5, 0xd2, 0x05,
	0xda, 0x1a, 0xb5, 0x97, 0x2d, 0x95, 0x3f, 0x13, 0xa7, 0x98, 0x3f, 0x83, 0xf8, 0x9d, 0xb5, 0xc6,
	0x8e, 0xf1, 0x0f, 0x47, 0x15, 0xe2, 0x2f, 0xc5, 0x24, 0xf9, 0x16, 0x16, 0xa5, 0x95, 0x7d, 0x8f,
	0x96, 0x31, 0x98, 0xfb, 0xa1, 0x9f, 0x36, 0xc2, 0x37, 0xcb, 0x60, 0xd1, 0xcb, 0xa1, 0x33, 0x92,
	0x4e, 0x27, 0xb9, 0x5a, 0x65, 0x74, 0x88, 0xd9, 0x74, 0x88, 0x59, 0xae, 0x07, 0x31, 0x2d, 0x55,
	0xf7, 0x02, 0x7e, 0xf5, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x16, 0xec, 0x44, 0xd2, 0x02, 0x00,
	0x00,
}
